### ISSUE TITLE
[meta] Register commands in the Drupal container.

### ISSUE THREAD

**Issue by jmolivas** [hechoendrupal/DrupalConsole#2593]
### Problem/Motivation

Register Drupal Console commands as services on the Drupal container.
### Why
- Improve command discover and take advantage of dependency injection.
#### Extend from `Symfony\Component\Console\Command\Command`

Add `use` keyword if not present

```
use Symfony\Component\Console\Command\Command;
```
#### Update class to extend from `Command`

```
class AwesomeCommand extends Command
```
#### Add `CommandTrait`

Add `use` keyword if not present

```
use Drupal\Console\Command\Shared\CommandTrait;
```

If command is using 

```
Drupal\Console\Command\Shared\ContainerAwareCommandTrait;
```

Update to 

```
Drupal\Console\Command\Shared\CommandTrait;
```

Add `use` trait:

```
use CommandTrait; 
```
#### Register command class as a service at `config/services/NAMESPACE.yml`

```
console.awesome:
   class: Drupal\Console\Command\AwesomeCommand
   arguments: ['@service_id', '@other_service_id', '@another_service_id']
   tags:
      - { name: drupal.command }
```

NOTE: If command already registered make sure you remove comment definition and confirm service name is prepended with `console.`. 
#### How to know which services to inject

Any call to:

```
$this->getService('SERVICE_NAME')
$this->getDrupalService('SERVICE_NAME')
$this->get('SERVICE_NAME')
\Drupal::service('SERVICE_NAME')
\Drupal::getContainer()->get('SERVICE_NAME')
$this->getApplication()->getContainerHelper()->get('SERVICE_NAME')
```

Should be added as `argument: ['@SERVICE_NAME']` on the service definition.
#### Inject service add use, property and constructor method.

```
...
use Vendor\Package\ServiceName;
...

    /**
     * @var ServiceName
     */
    protected $serviceName; 

    /**
     * AwesomeCommand constructor.
     * @param ServiceName $serviceName
     */
    public function __construct(ServiceName $serviceName) {
        $this->serviceName = $serviceName;
        parent::__construct();
    }
```

NOTES: 
- You can find the `Vendor\Package\ServiceName` of your service by executing from your Drupal 8 site `drupal container:debug SERVICE_NAME`.
- Make sure you call the `parent::__construct();` on the added `__construct`method.
#### Some methods and classes has been relocated to new service and maybe renamed, this is the table mapping those changes.

| Current | New Service name | New Method name |
| --- | --- | --- |
| $this->get('site')->loadLegacyFile | console.site | loadLegacyFile |
### How to test

Read setup instructions at https://gist.github.com/jmolivas/97bbd07f328217be3564a434c5bd2618
### Related documentation
- http://symfony.com/doc/current/console/commands_as_services.html
### Related issues:
- [meta] Register commands as services https://github.com/hechoendrupal/DrupalConsole/issues/2225
## Completed Namespace
- [x] Miscellaneous without Namespace. 
- [x] Breakpoints Namespace
- [x] Cache Namespace
- [x] Chain Namespace
- [x] Config Namespace
- [x] Create Namespace
- [x] Cron Namespace
- [x] Database Namespace
- [x] Develop Namespace (@langelhc) 
- [x] Entity Namespace
- [x] Exclude Namespace
- Exec Namespace (relocated to drupal-core)
- [x] File Namespace
- Generate Namespace (This will be done at the issue [#2679](https://github.com/hechoendrupal/DrupalConsole/issues/2679))
- [x] Image Namespace
- [x] Libraries Namespace
- [x] Locale Namespace (@novia713)
- [x] Migrate Namespace
- [x] Module Namespace (@enzolutions)
- [x] Multisite Namespace
- [x] Node Namespace
- [x] Queue Namespace
- [x] Rest Namespace
- [x] Router Namespace
- Self Namespace (relocated to drupal-launcher)
- Shared Namespace (traits will be updated as required)
- [x] Site Namespace (@jmolivas)
- [x] State Namespace
- [x] Test Namespace
- [x] Theme Namespace
- [x] Update Namespace
- [x] User Namespace
- [x] Views Namespace
- [x] Yaml Namespace
- Make sure you add a comment on the namespace you take to work to avoid working on same namespaces. 
- Make sure you get latest changes from Drupal Console repository for instructions [Keeping your fork up to date](http://docs.drupalconsole.com/en/contributing/keeping-your-fork-up-to-date.html)

**Comment by jmolivas** [comment]
I will take `Cache Namespace`.

**Comment by jmolivas** [comment]
I will take `Cache Namespace`.

**Comment by enzolutions** [comment]
Working in Chain

**Comment by enzolutions** [comment]
Working in Config

**Comment by jmolivas** [comment]
Working on Create

**Comment by jmolivas** [comment]
Working on Cron

**Comment by jmolivas** [comment]
Working on Database

**Comment by isramv** [comment]
Working on Image

**Comment by omero** [comment]
Working on `Update` namespace

**Comment by enzolutions** [comment]
Working in Entity

**Comment by enzolutions** [comment]
Working in field:info

**Comment by enzolutions** [comment]
Working in YAML commands

**Comment by enzolutions** [comment]
Working in Views commands

**Comment by novia713** [comment]
Working in Module commands

**Comment by enzolutions** [comment]
Working in user namepsace

**Comment by novia713** [comment]
working on Locale command

**Comment by enzolutions** [comment]
Working in theme

**Comment by jmolivas** [comment]
Working on `Exclude`

**Comment by jmolivas** [comment]
From `Develop` namespace I did complete:
* ExampleCommand
* ExampleContainerAwareCommand

**Comment by jmolivas** [comment]
Working on `Multisite`

**Comment by jmolivas** [comment]
Working on `Node`

**Comment by jmolivas** [comment]
Working on `Queue`

**Comment by jmolivas** [comment]
Working on `Router`

**Comment by jmolivas** [comment]
Working on `State`

**Comment by greg-1-anderson** [comment]
#2594 is a critical blocker; at a minimum, must be closed will-not-fix if not to be addressed.

**Comment by jmolivas** [comment]
@greg-1-anderson it will be fixed, but we need to have this one close and provide instructions and also help update/fix contributed commands providing DC integration.

**Comment by greg-1-anderson** [comment]
Just to be clear, #2594 is primarily a documentation issue; you need to decide what to do there in order to correctly document and close this meta-issue. I updated my comment there for clarity.

**Comment by jmolivas** [comment]
Working on `Site`

**Comment by jmolivas** [comment]
@greg-1-anderson looking at that and will discuss with the rest of the DC maintainers.

**Comment by novia713** [comment]
PR for `test` commands at #2657

**Comment by enzolutions** [comment]
Working in site namespace

**Comment by jmolivas** [comment]
@enzolutions `site:install` is done already ;)

**Comment by langelhc** [comment]
Working on Migrate

**Comment by langelhc** [comment]
Also working on Rest.

**Comment by langelhc** [comment]
Working on Test

**Comment by jmolivas** [comment]
@langelhc this was done by @novia713 PR => https://github.com/hechoendrupal/DrupalConsole/pull/2657

**Comment by langelhc** [comment]
@jmolivas sorry that was a mistake, Working on develop

**Comment by novia713** [comment]
PR for `translation` commands in Develop at https://github.com/hechoendrupal/DrupalConsole/pull/2830
